### ISSUE TITLE
Exit code 0

### ISSUE THREAD

**Issue by chrisjowen** [lewismj/cucumber#22]
Hi Mark, 

I thought I'd add another issue as you mentioned you might be free to work on this at the weekend. I also noticed that when the tests fail the exit code will still be 0 and as such our CI server is reporting failed tests as a passing build step.  

Cheers, Chris

**Comment by lewismj** [comment]
Had a quick look, in the cucumber plugin, I do the following:

~~~
  def run(  mainClass : String,
            parameters : List[String])(
            outputStrategy: OutputStrategy) : Int = {

    val logger : Logger = outputStrategy.asInstanceOf[LoggedOutput].logger

    val args  = jvmArgs ++  (mainClass :: parameters)
    val debug = args mkString " "
    logger.debug(s"[Jvm.run] Args $debug")

    Fork.java(ForkOptions(None,Some(outputStrategy)),args)
  }
~~~

i.e. I'm returning the exit code I get from the SBT Fork.java. This essentially is just saying if the command ran ok, i.e. 'sbt cucumber' ran ok, even if some of the tests failed.
I'll have a look at the sbt-runner (this hooks into 'sbt test') and see if there is something I can change there.

Looking at the 'sbt runner', this is a separate plugin for plugging into 'sbt test' rather than running as 'sbt cucumber', I can see...

~~~
case class FailureEvent(testName: String) extends Event {
  val description = s"[CucumberPlugin] Test $testName failed " +
                    "or undefined steps."
  val result = Result.Success
  val error: Throwable = null
}
~~~

Which looks wrong, obviously should be Result.Failure, I'll try changing that now.

**Comment by lewismj** [comment]
I made the change and now when I run 'sbt test' on a failing test, I will get the correct response. I've another couple of issues to look at. If I can do them quickly, I will bundle them into a release, otherwise I'll ship this change as a separate release very soon (hopefully within a day).

n.b. This is to the ```cucumber-runner```  and  ```sbt cucumber``` should return failure now (pending check-in and publish to maven) will update when available. 

I will update the documentation, the version of the plugin referenced in your plugins.sbt file will need to be updated to a new version (the examples will reference old versions, I'll update those).

**Comment by lewismj** [comment]
I've gone ahead and updated the project with the one change so that failure will be reported in ```sbt test``` now. I'll bundle up some other changes, hopefully another update in a day or so.

**Comment by chrisjowen** [comment]
Cheers Mike,

Thanks for the work you've done on this project its much appreciated, and this change is much appreciated. Is this now published to maven or just currently in master?

Incidentally, I was running `sbt cucumber` and not `sbt test` when I was getting an exit code 0. If the sbt-runner plugin is all related to sbt test then would this fix not have fixed when running `sbt cucumber`?

N.B. I also realised I called you Mark before, I apologise for that slip :)

**Comment by lewismj** [comment]
This should be corrected now. 

In the ```cucumber-plugin-example``` running ```sbt cucumber``` command, with a failing test yields:
~~~
[error] (*:cucumber) java.lang.IllegalStateException: Cucumber did not succeed and returned error =1
[error] Total time: 7 s, completed 05-Dec-2016 14:48:39
~~~

In the ```cucumber-runner-example``` running ```sbt test``` command, with a failing test
yields:
~~~
[error] Failed: Total 3, Failed 1, Errors 0, Passed 2
[error] Failed tests:
[error] 	com.waioeka.sbt.CucumberTestSuite
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 6 s, completed 05-Dec-2016 14:51:27
~~~

**Comment by lewismj** [comment]
n.b. Make sure you reference the latest plugin if you are using the plugin command:

~~~
addSbtPlugin("com.waioeka.sbt" % "cucumber-plugin" % "0.0.7")
~~~

Will take a look at the JVM options issue next.

**Comment by chrisjowen** [comment]
This is working as expected, thanks for the quick response.

**Comment by lewismj** [comment]
Thanks, I'll leave the open issue for a day or two in case of problems, then I'll close it down.
